### ISSUE TITLE
Definir Lista de User Stories com Testes de Aceitação

### ISSUE THREAD

**Issue by tacianosilva** [heitormedeiros/sige-pm#1]
O gerente deve colocar pelo menos dois requisitos por membro da equipe. Cada membro da equipe vai elaborar o user story e seus testes de aceitação.

**Comment by tacianosilva** [comment]
@heitormedeiros as tarefas para a equipe deve ser cadastrada com o label documentação.

**Comment by heitormedeiros** [comment]
@tacianosilva já fiz a alteração do label!

**Comment by heitormedeiros** [comment]
Foi definido cada User Storie dividido por colaborador!
