### ISSUE TITLE
Seguir o tutorial abaixo para produzir o CRUD para WEB

### ISSUE THREAD

**Issue by andregurgel** [heitormedeiros/sige-pm#12]
[Tutorial-CRUD](http://academyprogramming.blogspot.com.br/2015/08/crud-java-web-jsf-hibernate-primefaces.html)

@heitormedeiros 
@vandersonfabio 
@isaacJose

**Comment by tacianosilva** [comment]
@andregurgel crie tarefas específicas para a implementação do caso de uso base. O código deve ser enviado para o github.

**Comment by andregurgel** [comment]
[Novo Tutorial](http://www.ciceroednilson.com.br/criando-uma-aplicacao-java-com-jsf-primefaces-cdi-e-jpa-parte-1-introducao/)

**Comment by heitormedeiros** [comment]
Projeto Finalizado
