### ISSUE TITLE
Criar Plano de Release e Plano de Iteração

### ISSUE THREAD

**Issue by tacianosilva** [heitormedeiros/sige-pm#13]
Planejar datas e atividades para as iterações e o plano de release.

Um modelo do plano de release pode ser encontrado no link: [Plano de Release - Projeto APF](https://github.com/tacianosilva/apf-bsi/wiki/Plano-de-Release-e-Plano-de-Itera%C3%A7%C3%A3o)

**Comment by andregurgel** [comment]
O documento será produzido pelo atual gerente André juntamente com o Desenvolvedor Heitor

**Comment by andregurgel** [comment]
Documento finalizado, foi publicado na aba "wiki".
