### ISSUE TITLE
Definir os User Stories dos requisitos funcionais  5, 9 e 10. 

### ISSUE THREAD

**Issue by heitormedeiros** [heitormedeiros/sige-pm#2]
O colaborador Vanderson deve realizar a tarefa de construção dos User Stories com seus respectivos testes de aceitação.

**Comment by vandersonfabio** [comment]
Mãos à obra.

**Comment by vandersonfabio** [comment]
Feito. [User stories.docx](https://github.com/heitormedeiros/sige-pm/files/1356665/User.stories.docx)

**Comment by heitormedeiros** [comment]
Os documentos relacionados devem ser realizados no Google Drive para facilitar na padronização do documento, sendo realizados no documento nomeado User Stories na pasta Engenharia de Software 1.

**Comment by vandersonfabio** [comment]
Stories alteradas conforme exemplo do professor e adicionadas ao documento do GD. Também deixei o esqueleto para que os outros colaboradores possam cadastrar as demais stories.
