### ISSUE TITLE
Atualização do artefados

### ISSUE THREAD

**Issue by isaacJose** [heitormedeiros/sige-pm#22]
Os integrantes devem conferir e caso necessário atualizar os artefatos, gerando assim ao final um único documento em pdf, onde o mesmo deve ser enviado via SIGAA.

Artefatos:

Lista de User Stories com Testes de Aceitação;
Modelo de Dados (Diagrama de Entidade-Relacionamento) ;
Modelo Relacional com Dicionário de Dados;
Arquitetura do Software;
Modelo Conceitual (Diagrama de Classes UML);
Plano de Release
Plano de Interação
Relatório de Testes dos User Stories implementados;
Testes de Unidade dos User Stories implementados.

**Comment by heitormedeiros** [comment]
Concluído.
