### ISSUE TITLE
Definir os User Stories dos requisitos funcionais 1, 2 e 3.

### ISSUE THREAD

**Issue by heitormedeiros** [heitormedeiros/sige-pm#3]
O colaborador André Gurgel deve realizar a tarefa de construção dos User Stories com seus respectivos testes de aceitação.

**Comment by andregurgel** [comment]
[RF 1, 2 e 3.docx](https://github.com/heitormedeiros/sige-pm/files/1356766/RF.1.2.e.3.docx)

**Comment by heitormedeiros** [comment]
Os documentos relacionados devem ser realizados no Google Drive para facilitar na padronização do documento, sendo realizados no documento nomeado User Stories na pasta Engenharia de Software 1.

**Comment by andregurgel** [comment]
Acabei de adicionar os User Stories que fiquei responsável no documento existente no Google Drive, sendo assim, estou fechando a tarefa.
