### ISSUE TITLE
Definir os User Stories dos requisitos funcionais 4, 6, 7 e 8.

### ISSUE THREAD

**Issue by heitormedeiros** [heitormedeiros/sige-pm#4]
O colaborador Isaac José deve realizar a tarefa de construção dos User Stories com seus respectivos testes de aceitação.

**Comment by isaacJose** [comment]
[BD-User.docx](https://github.com/heitormedeiros/sige-pm/files/1356673/BD-User.docx)

**Comment by heitormedeiros** [comment]
Os documentos relacionados devem ser realizados no Google Drive para facilitar na padronização do documento, sendo realizados no documento nomeado User Stories na pasta Engenharia de Software 1.

**Comment by isaacJose** [comment]
https://docs.google.com/document/d/1pnfu-PT2-HtdSfui9If5KCgVIQwKuVtd8UD2NiiRXAk/edit
