### ISSUE TITLE
Criar Diagrama de Entidade Relacionamento

### ISSUE THREAD

**Issue by tacianosilva** [heitormedeiros/sige-pm#5]
O gerente @heitormedeiros deve definir quem vai trabalhar nesta tarefa, pode ser um ou mais membros. A equipe deve informar quanto tempo levou para terminar a tarefa.

**Comment by heitormedeiros** [comment]
A equipe completa deve se reunir na terça-feira dia 03/09/2017 as 17horas na bilbioteca do ceres para criar o diagrama entidade relacionamento do projeto SIGE.

**Comment by heitormedeiros** [comment]
[DER - SIGE.pdf](https://github.com/heitormedeiros/sige-pm/files/1356748/DER.-.SIGE.pdf)
