### ISSUE TITLE
Criar Diagrama de Entidade Relacionamento

### ISSUE THREAD

**Issue by heitormedeiros** [heitormedeiros/sige-pm#6]
Toda a equipe deve se reunir Segunda-Feira as 15 horas na biblioteca do Ceres para realizar o diagrama entidade relacionamento.

**Comment by tacianosilva** [comment]
@heitormedeiros porque você criou novamente uma tarefa que já existia?

**Comment by heitormedeiros** [comment]
Eu queria mudar o dia da reunião de criação do diagrama entidade relacionamento para segunda feira, mas não consegui alterar o texto no projeto anterior. Estou me adaptando a ferramenta, ainda com bastante dificuldade. Mas já nos reunimos e realizamos a tarefa. Gostaria de saber para onde enviamos as tarefas concluídas (User Stories) e DER ?
