### ISSUE TITLE
Criar Modelo Relacional com Dicionário de Dados

### ISSUE THREAD

**Issue by heitormedeiros** [heitormedeiros/sige-pm#9]
O Colaborador André deve realizar a o modelo relacional e criar o dicionário de dados, a partir do diagrama entidade relacionamento realizado pela equipe na segunda-feira dia 02/10/2017.

**Comment by andregurgel** [comment]
Modelo relacional finalizado e pronto para revisão, o arquivo do mesmo está na pasta compartilhada do Drive.

**Comment by andregurgel** [comment]
Dicionario de Dados finalizado e pronto para revisão, o arquivo do mesmo está na pasta compartilhada do Drive.
